version: 2
sources:
    - name: source
      database: WALMART
      schema: BRONZE
      tables:
        - name: STORES
        - name: DEPARTMENT
        - name: FACT

models:
  - name: walmart_store_dim
  - name: walmart_department_dim
  - name: walmart_department_fact
  - name: walmart_date_dim
    columns:
    - name: date_id
      tests:
        - unique
        - not_null
  - name: stg_fact_table